/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-OCR.h
 #	source generated by 4D Plugin Wizard
 #	Project : OCR
 #	author : miyako
 #	2021/01/03
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_OCR_H
#define PLUGIN_OCR_H

#include "4DPluginAPI.h"
#include "C_TEXT.h"
#include "support/4DPlugin-JSON.h"

#if VERSIONWIN

#include <vector>

#include "winrt/base.h"
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Storage.Pickers.h>
#include <winrt/Windows.Storage.Streams.h>
#include <winrt/Windows.Graphics.Imaging.h>
#include <winrt/Windows.Media.FaceAnalysis.h>
#include <winrt/Windows.Media.Ocr.h>

#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.Devices.Enumeration.h>
#include <winrt/Windows.Media.Devices.h>

#include <winrt/Windows.Security.Cryptography.h>
#include <winrt/Windows.Globalization.h>

#include <experimental\coroutine>
#include <experimental\resumable>
#include <pplawait.h>

#include <process.h>

#endif

#pragma mark -

void ocr_picture_data(PA_PluginParameters params);
void ocr_get_info(PA_PluginParameters params);

#endif /* PLUGIN_OCR_H */
